export const LOGIN_REQUEST ="LOGIN_REQUEST";
export const LOGIN_SUCCESS ="LOGIN_SUCCESS";
export const LOGIN_FAIL ="LOGIN_FAIL";

export const CREATE_USER_REQUEST ="CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS ="CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL ="CREATE_USER_FAIL";

export const DETAIL_USER_REQUEST ="DETAIL_USER_REQUEST";
export const DETAIL_USER_SUCCESS ="DETAIL_USER_SUCCESS";
export const DETAIL_USER_FAIL ="DETAIL_USER_FAIL";

export const LOGOUT_SUCCESS ="LOGOUT_SUCCESS";
export const LOGOUT_FAIL ="LOGOUT_FAIL";

export const CLEAR_ERRORS="CLEAR_ERRORS";